### ISSUE TITLE
AddressInput for google places with new input styling

### ISSUE THREAD

**Issue by jgrubard** [rentalutions/elements#68]
## Component Request
a replacement for our current google places input to match the new input UI.

### Component Name
AddressInput

### Use case
We will be able to use this component to replace all older styles. We should consider how we send back the address data once retrieved.

### Design

Current AddressInput:

Untouched:
<img width="616" alt="Screen Shot 2020-04-02 at 4 13 06 PM" src="https://user-images.githubusercontent.com/29084739/78300297-ddccf980-74fc-11ea-91f5-ca4ee251b6f6.png">

On Focus:
<img width="624" alt="Screen Shot 2020-04-02 at 4 11 47 PM" src="https://user-images.githubusercontent.com/29084739/78300310-e291ad80-74fc-11ea-8c88-4685fb6d17d4.png">

Once we start typing:
<img width="619" alt="Screen Shot 2020-04-02 at 4 11 58 PM" src="https://user-images.githubusercontent.com/29084739/78300319-e6253480-74fc-11ea-9fb0-75f087dbedbf.png">

**Comment by pkrawc** [comment]
Hey @jgrubard,

I'm wondering if this is better left to you and the client application instead of a special input. I'm sort of against a single-use component unless we see a lot of usages.

If this repo is currently made up of elements (in the atomic design sense), I think this request is more a  molecule.

I imagine this using the `Input` & `Card` components along with a custom hook. I think this is better because there are implementation details of google autocomplete that I don't want the elements repo to manage.

A simple `useAutoComplete` hook could be as follows

```javascript
function useAutoComplete(query) {
  const autocompleteRef = useRef()
  const [predictions, set] = useState([])
  if (autocompleteRef.current === "undefined") {
    autocompleteRef.current = new google.maps.AutocompleteService()
  }
  const getPredictions = useCallback(() => {
    autocompleteRef.current.predictions(
      { input: query },
      (predictions) => set(predictions)
    )
  }, [query])
  useEffect(() => { getPredictions() }, [query])
  return predictions
}
```

**Comment by pkrawc** [comment]
This issue is addressed by the following package.

`@rent_avail/autocomplete`
