### ISSUE TITLE
Select component doesn't render as expected inside dialogs

### ISSUE THREAD

**Issue by pkrawc** [rentalutions/elements#95]
## Prerequisites

`@rent_avail/select@0.1.8`, `@rent_avail/dialog@0.1.8`

## Step to reproduce (actual behavior)

Placing a select inside a confirmation dialog. When opening the select component the list renders both wider than it's input and over the input. When selecting an option in the list it closes the modal right away.

### Expected behavior

It shouldn't close the modal right away, and it should render well inside any portal contained element.

**Comment by jgrubard** [comment]
@pkrawc not a bug, just a `console.log` that was left in. I didn't think this needed a separate issue created since you mentioned you were still working on the `SelectInput`. Let me know if I should create a new issue for this.

lonely `console.log(target.dataset.value)` on line `356`:
https://github.com/rentalutions/elements/blob/release/packages/select/src/index.js#L356
